import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/Components/Header/Header";
import { Inter } from 'next/font/google'
import HeaderSocialLinks from "@/Components/HeaderSocialLinks/HeaderSocialLinks";
import Footer from "@/Components/Footer/Footer";

// If loading a variable font, you don't need to specify the font weight
const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
})

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  return (
    <html lang="ru">
      <head>
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no"
        >
        </meta>
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased 
        ${inter.className} flex flex-col min-h-screen`}
      >
        <HeaderSocialLinks />
        <Header />
        <main className="flex-grow">
          {children}
        </main>
          <Footer />
      </body>
    </html>
  );
}
